export enum CollectionCategory {
  COMPANY_INFO = 'COMPANY_INFO',
  DEPARTMENTS = 'DEPARTMENTS',
  EMPLOYEES = 'EMPLOYEES',
  WORKFLOWS = 'WORKFLOWS',
  SALARY = 'SALARY',
  SCHEDULING = 'SCHEDULING',
  FEATURES = 'FEATURES',
  SPECIAL_REQUIREMENTS = 'SPECIAL_REQUIREMENTS',
  PRIORITIES = 'PRIORITIES',
  INTEGRATIONS = 'INTEGRATIONS',
}
