export enum NotificationType {
  NEW_PROJECT = 'NEW_PROJECT',
  COLLECTION_COMPLETE = 'COLLECTION_COMPLETE',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  REVIEW_NEEDED = 'REVIEW_NEEDED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  COMMENT = 'COMMENT',
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
}
