export enum ProjectStatus {
  COLLECTING = 'COLLECTING',
  COLLECTED = 'COLLECTED',
  REVIEWING = 'REVIEWING',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ON_HOLD = 'ON_HOLD',
}
